import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

export const exercisesSeedData = [
  // Strength Exercises
  {
    name: 'Bench Press',
    description: 'Classic chest building exercise using a barbell',
    instructions:
      '1. Lie on bench with feet flat on floor\n2. Grip barbell slightly wider than shoulders\n3. Lower bar to chest\n4. Press up explosively\n5. Repeat for desired reps',
    muscleGroups: JSON.stringify(['chest', 'triceps', 'shoulders']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
    isTrackedByDefault: true, // Base exercise for tracking
  },
  {
    name: 'Incline Bench Press',
    description: 'Chest press on an incline bench to target upper chest',
    instructions:
      '1. Set bench to 30–45° incline\n2. Grip bar slightly wider than shoulders\n3. Lower to upper chest\n4. Press up and slightly back\n5. Keep shoulder blades retracted',
    muscleGroups: JSON.stringify(['chest', 'triceps', 'shoulders']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Close-Grip Bench Press',
    description: 'Narrow grip bench press emphasizing triceps',
    instructions:
      '1. Grip bar just inside shoulder width\n2. Keep elbows close\n3. Lower to lower chest\n4. Press up powerfully',
    muscleGroups: JSON.stringify(['triceps', 'chest', 'shoulders']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Decline Bench Press',
    description: 'Press on a decline bench targeting lower chest',
    instructions: '1. Set decline bench\n2. Lower bar to lower chest\n3. Press up under control',
    muscleGroups: JSON.stringify(['chest', 'triceps']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Dumbbell Bench Press',
    description: 'Chest press using dumbbells for greater range of motion',
    instructions: '1. Start with dumbbells over chest\n2. Lower with elbows at ~45°\n3. Press up and squeeze chest',
    muscleGroups: JSON.stringify(['chest', 'triceps', 'shoulders']),
    equipment: 'Гантелі',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Cable Crossover',
    description: 'Cable fly focusing on chest contraction',
    instructions:
      '1. Set pulleys at shoulder height\n2. Step forward\n3. Bring handles together in arc\n4. Stretch and squeeze each rep',
    muscleGroups: JSON.stringify(['chest']),
    equipment: 'Кросовер',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Pec Deck',
    description: 'Machine fly for chest isolation',
    instructions: '1. Adjust seat so elbows align with pads\n2. Bring arms together\n3. Squeeze chest; control return',
    muscleGroups: JSON.stringify(['chest']),
    equipment: 'Тренажер',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Barbell Row',
    description: 'Bent-over row for back thickness',
    instructions:
      '1. Hinge at hips with flat back\n2. Row bar to lower chest/upper abs\n3. Control down; keep torso stable',
    muscleGroups: JSON.stringify(['back', 'biceps']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
    isTrackedByDefault: true,
  },
  {
    name: 'Seated Cable Row',
    description: 'Horizontal row on cable machine',
    instructions: '1. Sit tall\n2. Pull handle to torso\n3. Squeeze shoulder blades\n4. Control forward',
    muscleGroups: JSON.stringify(['back', 'biceps']),
    equipment: 'Блоки',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Lat Pulldown (Wide Grip)',
    description: 'Vertical pull targeting lats',
    instructions: '1. Grip bar wide\n2. Pull to upper chest\n3. Drive elbows down\n4. Control up fully',
    muscleGroups: JSON.stringify(['back', 'biceps']),
    equipment: 'Блоки',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Lat Pulldown (Close Grip)',
    description: 'Close/neutral grip pulldown',
    instructions: '1. Use V-handle\n2. Pull to chest while leaning slightly back\n3. Squeeze lats at bottom',
    muscleGroups: JSON.stringify(['back', 'biceps']),
    equipment: 'Блоки',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'T-Bar Row',
    description: 'Landmine/T‑bar row for mid-back',
    instructions: '1. Hinge at hips\n2. Row handle to chest\n3. Keep elbows close',
    muscleGroups: JSON.stringify(['back', 'biceps']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Face Pull',
    description: 'Cable pull to face for rear delts and rotators',
    instructions: '1. Use rope at forehead height\n2. Pull to face with external rotation\n3. Control back',
    muscleGroups: JSON.stringify(['shoulders', 'back']),
    equipment: 'Блоки',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Romanian Deadlift',
    description: 'Hip hinge emphasizing hamstrings and glutes',
    instructions:
      '1. Soft knees\n2. Push hips back\n3. Keep bar close to legs\n4. Stretch hamstrings\n5. Drive hips forward',
    muscleGroups: JSON.stringify(['hamstrings', 'glutes', 'back']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Sumo Deadlift',
    description: 'Wide-stance deadlift variation',
    instructions: '1. Wide stance, toes out\n2. Grip inside knees\n3. Drive knees out and hips forward',
    muscleGroups: JSON.stringify(['legs', 'glutes', 'back']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Hip Thrust',
    description: 'Glute-focused hip extension with barbell',
    instructions: '1. Upper back on bench\n2. Bar over hips\n3. Extend hips to full lockout\n4. Pause and squeeze',
    muscleGroups: JSON.stringify(['glutes', 'hamstrings']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Leg Press',
    description: 'Compound machine press for legs',
    instructions: '1. Feet shoulder width\n2. Lower to ~90° knee bend\n3. Press without locking knees',
    muscleGroups: JSON.stringify(['legs', 'glutes']),
    equipment: 'Тренажер',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Hack Squat',
    description: 'Machine squat variation for quads',
    instructions: '1. Keep back on pad\n2. Descend deep with knees tracking\n3. Drive up through mid‑foot',
    muscleGroups: JSON.stringify(['quads', 'glutes']),
    equipment: 'Тренажер',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Bulgarian Split Squat',
    description: 'Rear‑foot elevated split squat',
    instructions: '1. Rear foot on bench\n2. Drop back knee down\n3. Keep torso tall\n4. Drive through front heel',
    muscleGroups: JSON.stringify(['quads', 'glutes']),
    equipment: 'Гантелі',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Walking Lunge',
    description: 'Alternating forward lunges while walking',
    instructions: '1. Step forward\n2. Lower until both knees ~90°\n3. Push through front heel',
    muscleGroups: JSON.stringify(['quads', 'glutes', 'hamstrings']),
    equipment: 'Гантелі',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Leg Extension',
    description: 'Isolation for quadriceps',
    instructions: '1. Adjust pad above ankles\n2. Extend knees fully\n3. Control down',
    muscleGroups: JSON.stringify(['quads']),
    equipment: 'Тренажер',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Leg Curl',
    description: 'Hamstring curl machine',
    instructions: '1. Align knee with machine pivot\n2. Curl pad toward glutes\n3. Control back',
    muscleGroups: JSON.stringify(['hamstrings']),
    equipment: 'Тренажер',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Standing Calf Raise',
    description: 'Calf raise performed standing',
    instructions: '1. Full stretch at bottom\n2. Press up to peak contraction\n3. Pause briefly',
    muscleGroups: JSON.stringify(['calves']),
    equipment: 'Тренажер',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Seated Calf Raise',
    description: 'Calf raise performed seated',
    instructions: '1. Adjust thigh pad\n2. Raise heels high\n3. Lower to deep stretch',
    muscleGroups: JSON.stringify(['calves']),
    equipment: 'Тренажер',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Hammer Curl',
    description: 'Neutral grip curl targeting brachialis',
    instructions: '1. Hold dumbbells neutral\n2. Curl without rotation\n3. Control down',
    muscleGroups: JSON.stringify(['biceps']),
    equipment: 'Гантелі',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Incline Dumbbell Curl',
    description: 'Biceps curl on incline bench for long head',
    instructions: '1. Lean back on incline bench\n2. Let arms fully stretch\n3. Curl and squeeze',
    muscleGroups: JSON.stringify(['biceps']),
    equipment: 'Гантелі',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Triceps Pushdown',
    description: 'Cable pushdown for triceps',
    instructions: '1. Use rope or straight bar\n2. Keep elbows by sides\n3. Extend fully\n4. Control up',
    muscleGroups: JSON.stringify(['triceps']),
    equipment: 'Блоки',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Skull Crushers',
    description: 'Lying EZ‑bar triceps extensions',
    instructions: '1. Lower bar toward forehead\n2. Keep elbows in\n3. Extend to lockout',
    muscleGroups: JSON.stringify(['triceps']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Overhead Triceps Extension',
    description: 'Overhead extension with dumbbell or cable',
    instructions: '1. Elbows high\n2. Lower behind head\n3. Extend fully',
    muscleGroups: JSON.stringify(['triceps']),
    equipment: 'Гантелі',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Chin-up',
    description: 'Underhand grip pull-up variation',
    instructions: '1. Grip underhand shoulder width\n2. Pull until chin over bar\n3. Lower under control',
    muscleGroups: JSON.stringify(['back', 'biceps']),
    equipment: 'Власна вага',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Dumbbell Shoulder Press',
    description: 'Overhead press using dumbbells',
    instructions: '1. Start seated\n2. Press dumbbells overhead\n3. Control to ears level',
    muscleGroups: JSON.stringify(['shoulders', 'triceps']),
    equipment: 'Гантелі',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Lateral Raise',
    description: 'Dumbbell raise to the side for medial delts',
    instructions: '1. Slight elbow bend\n2. Raise to shoulder height\n3. Control down',
    muscleGroups: JSON.stringify(['shoulders']),
    equipment: 'Гантелі',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Rear Delt Fly',
    description: 'Bent-over dumbbell fly for rear delts',
    instructions: '1. Hinge at hips\n2. Raise arms out to sides\n3. Squeeze rear delts',
    muscleGroups: JSON.stringify(['shoulders', 'back']),
    equipment: 'Гантелі',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Smith Machine Squat',
    description: 'Squat using Smith machine',
    instructions: '1. Feet slightly forward\n2. Descend under control\n3. Drive up through mid‑foot',
    muscleGroups: JSON.stringify(['quads', 'glutes']),
    equipment: 'Смітт',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Smith Machine Bench Press',
    description: 'Bench press using Smith machine',
    instructions: '1. Set safeties\n2. Lower to chest\n3. Press up; keep wrists stacked',
    muscleGroups: JSON.stringify(['chest', 'triceps']),
    equipment: 'Смітт',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Hyperextension',
    description: 'Back extension on Roman chair',
    instructions: '1. Hips over pad\n2. Lower with neutral spine\n3. Extend by squeezing glutes',
    muscleGroups: JSON.stringify(['back', 'glutes', 'hamstrings']),
    equipment: 'Тренажер',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Hanging Leg Raise',
    description: 'Core exercise lifting legs while hanging',
    instructions: '1. Hang from bar\n2. Raise legs to hip level or higher\n3. Control down, avoid swinging',
    muscleGroups: JSON.stringify(['abs', 'hip flexors']),
    equipment: 'Турнік',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Squat',
    description: 'Fundamental lower body exercise targeting legs and glutes',
    instructions:
      '1. Stand with feet shoulder-width apart\n2. Lower body by bending knees and hips\n3. Keep chest up and knees tracking over toes\n4. Descend until thighs parallel to floor\n5. Drive through heels to return to start',
    muscleGroups: JSON.stringify(['legs', 'glutes']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
    isTrackedByDefault: true, // Base exercise for tracking
  },
  {
    name: 'Deadlift',
    description: 'Full-body compound exercise focusing on posterior chain',
    instructions:
      '1. Stand with feet hip-width apart\n2. Bend at hips and knees to grip bar\n3. Keep back straight and chest up\n4. Drive through heels and extend hips\n5. Stand tall with shoulders back',
    muscleGroups: JSON.stringify(['back', 'legs', 'glutes']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
    isTrackedByDefault: true, // Base exercise for tracking
  },
  {
    name: 'Pull-up',
    description: 'Upper body pulling exercise using body weight',
    instructions:
      '1. Hang from pull-up bar with arms extended\n2. Pull body up until chin over bar\n3. Lower with control to starting position\n4. Keep core engaged throughout movement',
    muscleGroups: JSON.stringify(['back', 'biceps']),
    equipment: 'Власна вага',
    category: 'strength' as const,
    isCustom: false,
    isTrackedByDefault: true, // Base exercise for tracking
  },
  {
    name: 'Push-up',
    description: 'Classic bodyweight chest and triceps exercise',
    instructions:
      '1. Start in plank position\n2. Lower body until chest nearly touches floor\n3. Push up to starting position\n4. Keep body in straight line throughout',
    muscleGroups: JSON.stringify(['chest', 'triceps', 'shoulders']),
    equipment: 'Власна вага',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Dumbbell Row',
    description: 'Unilateral back exercise using dumbbells',
    instructions:
      '1. Place one knee and hand on bench\n2. Hold dumbbell in opposite hand\n3. Pull elbow back and up\n4. Squeeze shoulder blade at top\n5. Lower with control',
    muscleGroups: JSON.stringify(['back', 'biceps']),
    equipment: 'Гантелі',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Overhead Press',
    description: 'Shoulder building exercise pressing weight overhead',
    instructions:
      '1. Stand with feet shoulder-width apart\n2. Hold barbell at shoulder level\n3. Press straight up overhead\n4. Lower with control to shoulders\n5. Keep core tight throughout',
    muscleGroups: JSON.stringify(['shoulders', 'triceps']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
    isTrackedByDefault: true, // Base exercise for tracking
  },
  {
    name: 'Barbell Curl',
    description: 'Isolation exercise targeting the biceps',
    instructions:
      '1. Stand with feet hip-width apart\n2. Hold barbell with underhand grip\n3. Curl bar up to chest level\n4. Squeeze biceps at top\n5. Lower with control',
    muscleGroups: JSON.stringify(['biceps']),
    equipment: 'Штанга',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Tricep Dips',
    description: 'Bodyweight exercise targeting triceps',
    instructions:
      '1. Place hands on edge of bench or chair\n2. Lower body by bending elbows\n3. Push back up to starting position\n4. Keep elbows close to body',
    muscleGroups: JSON.stringify(['triceps']),
    equipment: 'Власна вага',
    category: 'strength' as const,
    isCustom: false,
  },
  {
    name: 'Plank',
    description: 'Core stability exercise holding a static position',
    instructions:
      '1. Start in push-up position\n2. Lower to forearms\n3. Hold straight line from head to heels\n4. Keep core engaged and breathe normally\n5. Hold for desired time',
    muscleGroups: JSON.stringify(['abs']),
    equipment: 'Власна вага',
    category: 'strength' as const,
    isCustom: false,
  },

  // Cardio Exercises (limited to core set up to 10)
  {
    name: 'Running',
    description: 'Classic cardiovascular exercise',
    instructions: 'Maintain steady breathing; warm up and cool down',
    muscleGroups: JSON.stringify(['cardio', 'legs']),
    equipment: '',
    category: 'cardio' as const,
    isCustom: false,
  },
  {
    name: 'Cycling',
    description: 'Low-impact cardiovascular exercise',
    instructions: 'Adjust seat; keep steady cadence',
    muscleGroups: JSON.stringify(['cardio', 'legs']),
    equipment: 'Кардіо',
    category: 'cardio' as const,
    isCustom: false,
  },
  {
    name: 'Rowing Machine',
    description: 'Cardio with full-body involvement',
    instructions: 'Drive with legs, then back and arms',
    muscleGroups: JSON.stringify(['cardio', 'back', 'legs']),
    equipment: 'Тренажер',
    category: 'cardio' as const,
    isCustom: false,
  },
  {
    name: 'Elliptical',
    description: 'Low-impact cardio trainer',
    instructions: 'Keep steady rhythm and posture',
    muscleGroups: JSON.stringify(['cardio']),
    equipment: 'Тренажер',
    category: 'cardio' as const,
    isCustom: false,
  },
  {
    name: 'Stair Climber',
    description: 'Stepping cardio workout',
    instructions: 'Short steps, steady pace',
    muscleGroups: JSON.stringify(['cardio', 'legs']),
    equipment: 'Тренажер',
    category: 'cardio' as const,
    isCustom: false,
  },
  {
    name: 'Burpees',
    description: 'Full-body high-intensity exercise',
    instructions: 'Squat, plank, push-up, jump',
    muscleGroups: JSON.stringify(['cardio', 'chest', 'legs']),
    equipment: 'Власна вага',
    category: 'cardio' as const,
    isCustom: false,
  },
  {
    name: 'Jump Rope',
    description: 'Jump rope conditioning',
    instructions: 'Light on feet, steady tempo',
    muscleGroups: JSON.stringify(['cardio', 'legs']),
    equipment: 'Інше',
    category: 'cardio' as const,
    isCustom: false,
  },
  {
    name: 'Jumping Jacks',
    description: 'Simple cardio warm-up',
    instructions: 'Arms overhead; soft landings',
    muscleGroups: JSON.stringify(['cardio']),
    equipment: 'Власна вага',
    category: 'cardio' as const,
    isCustom: false,
  },

  // Flexibility Exercises (minimal core set)
  {
    name: 'Downward Dog',
    description: 'Yoga pose that stretches and strengthens',
    instructions: 'Lift hips up and back; breathe deeply',
    muscleGroups: JSON.stringify(['back', 'legs']),
    equipment: 'Власна вага',
    category: 'flexibility' as const,
    isCustom: false,
  },
  {
    name: "Child's Pose",
    description: 'Relaxing yoga pose for back and hips',
    instructions: 'Sit back on heels; reach forward; relax',
    muscleGroups: JSON.stringify(['back']),
    equipment: 'Власна вага',
    category: 'flexibility' as const,
    isCustom: false,
  },
  {
    name: 'Hamstring Stretch',
    description: 'Posterior thigh stretch',
    instructions: 'Lean to extended leg; hold 30s',
    muscleGroups: JSON.stringify(['legs']),
    equipment: 'Власна вага',
    category: 'flexibility' as const,
    isCustom: false,
  },

  // Sport-specific exercises (minimal)
  {
    name: 'Box Jumps',
    description: 'Plyometric jump onto a box',
    instructions: 'Jump and land softly; step down',
    muscleGroups: JSON.stringify(['legs', 'glutes']),
    equipment: 'Інше',
    category: 'sport' as const,
    isCustom: false,
  },
  {
    name: 'Medicine Ball Slam',
    description: 'Explosive slam with med ball',
    instructions: 'Slam ball with core engagement',
    muscleGroups: JSON.stringify(['abs', 'shoulders', 'back']),
    equipment: 'Інше',
    category: 'sport' as const,
    isCustom: false,
  },
]

export async function seedExercises() {
  console.log('🌱 Seeding exercises...')

  for (const exercise of exercisesSeedData) {
    const existing = await prisma.exercise.findFirst({
      where: { name: exercise.name, isCustom: false },
      select: { id: true },
    })

    if (existing) {
      await prisma.exercise.update({
        where: { id: existing.id },
        data: {
          description: exercise.description,
          instructions: exercise.instructions,
          muscleGroups: exercise.muscleGroups,
          equipment: exercise.equipment,
          category: exercise.category,
          isCustom: false,
          isTrackedByDefault: Boolean((exercise as any).isTrackedByDefault),
        },
      })
    } else {
      await prisma.exercise.create({ data: exercise })
    }
  }

  const count = await prisma.exercise.count({ where: { isCustom: false } })
  console.log(`✅ Seeded/updated ${count} system exercises`)
}

export default seedExercises
